Add: Detail screen
thanhnn16/allure_spa_expo pull request #14
Opened 2024-09-23 09:40 UTC by ptnzzn

Add detail screen, add icons, news fonts.

2024-09-23 14:23 UTC, thanhnn16 requested changes
Nhân check nha. Nào done đánh dấu xong là oke.
Với comment mấy cái Thành hỏi zô nha

2024-09-23 14:23 UTC, thanhnn16 commented on app/(tabs)/(home)/details/[id].tsx
> +const styles = StyleSheet.create({
Dùng thư viện react native ui  lib nha Nhân

2024-09-23 14:23 UTC, thanhnn16 commented on app/(tabs)/(home)/index.tsx
> +const styles = StyleSheet.create({
hong dùng style sheet nha. cứ chơi thư viện ui lib cho đồng bộ

2024-09-23 14:23 UTC, thanhnn16 commented on assets/icons/comment.png
Biểu tượng svg hết nha

2024-09-23 14:23 UTC, thanhnn16 commented on tsconfig.json
> +    "**/*.tsx"
sao xoá mấy này z nhân

2024-09-23 14:23 UTC, thanhnn16 commented on app.json
> +    ]
sao Nhân xoá này zây
"experiments": {

2024-09-24 04:31 UTC, ptnzzn commented on app/(tabs)/(home)/details/[id].tsx
> +const styles = StyleSheet.create({
để nhân đổi lại hết, hqua còn hơi lú

2024-09-24 12:21 UTC, ptnzzn commented on assets/icons/comment.png
cái này nhân nghiên cứu thêm nha, chứ vẫn chưa hiểu lắm

2024-09-24 12:22 UTC, ptnzzn commented on tsconfig.json
> +    "**/*.tsx"
ụa cgi z nhân hong nhớ nữa

2024-09-24 12:22 UTC, ptnzzn commented on app.json
> +    ]
hông nhớ sao xoá lun huhu

2024-09-24 14:23 UTC, thanhnn16 commented on assets/icons/comment.png
https://docs.expo.dev/versions/latest/sdk/svg/
Cứ vô docs của trang expo mà đọc. Đừng có AI mấy khúc này.

2024-09-24 14:23 UTC, thanhnn16 commented on tsconfig.json
> +    "**/*.tsx"
Hong nhớ restore đi Nhân

2024-09-24 14:24 UTC, thanhnn16 commented on app.json
> +    ]
Xài AI bấm tab đúng k

2024-09-24 17:34 UTC, ptnzzn commented on app.json
> +    ]
do cài thư viện gì lỗi á xong nhân reset lun nên mới xoá z thì phải

2024-09-24 17:36 UTC, ptnzzn commented on tsconfig.json
> +    "**/*.tsx"
ụa restore sao z

2024-09-25 14:22 UTC, thanhnn16 requested changes
Check hết nha.
lưu ý đọc comment với docs

2024-09-25 14:22 UTC, thanhnn16 commented on app/(tabs)/(home)/index.tsx
> +const styles = StyleSheet.create({
đã sửa đâu mà nhấn xong z nhân

2024-09-25 14:22 UTC, thanhnn16 commented on components/texts/TextSFProBold.tsx
> +interface TextSFProBoldProps extends TextProps {
https://docs.expo.dev/develop/user-interface/fonts/
Đặt font mặc định

2024-09-25 14:22 UTC, thanhnn16 commented on components/texts/TextSFProBold.tsx
> +const TextSFProBold: React.FC<TextSFProBoldProps> = ({ fontSize, color, style, ...props }) => {
https://wix.github.io/react-native-ui-lib/docs/foundation/style
https://wix.github.io/react-native-ui-lib/docs/components/basic/Text

dùng đây nè nhân. k cần tạo custom text vậy đâu

2024-09-25 14:22 UTC, thanhnn16 commented on components/texts/TextSFProMedium.tsx
> +interface TextSFProMedium extends TextProps {
như trên

2024-09-25 14:22 UTC, thanhnn16 commented on components/texts/TextSFProRegular.tsx
như trên

2024-09-25 14:22 UTC, thanhnn16 commented on tsconfig.json
> +    "**/*.tsx"
chưa làm được sao mark resolved zậy

2024-09-25 14:22 UTC, thanhnn16 commented on tsconfig.json
> +    "**/*.tsx"
copy mã cũ bỏ vô lại thôi

2024-09-26 11:10 UTC, ptnzzn commented on components/texts/TextSFProBold.tsx
> +const TextSFProBold: React.FC<TextSFProBoldProps> = ({ fontSize, color, style, ...props }) => {
cái này oke ời

2024-09-29 06:45 UTC, merged