Quanghieu
thanhnn16/allure_spa_expo pull request #15
Opened 2024-09-23 13:27 UTC by quhie

"Update Login, Register, and add Onboarding page"

2024-09-23 13:56 UTC, thanhnn16 requested changes
Em Hiếu check lại nha. Có comment đó.
Cái nào done rồi mark resolve là xong.
Không hiểu cứ comment lại là đc

2024-09-23 13:56 UTC, thanhnn16 commented on app/authen/pages/Onboarding.tsx
> +const styles = StyleSheet.create({
K dùng này. Dùng rn ui-lib. có gửi link trong readme.md,
hoặc search google.

2024-09-23 13:56 UTC, thanhnn16 commented on app/authen/pages/Register.tsx
> +const styles = StyleSheet.create({
Tương tự luôn. Không dùng StyleSheet này. Dùng thư viện rn ui lib.

2024-09-23 13:56 UTC, thanhnn16 commented on git
Xoá file này lun đi nè.

2024-09-23 14:04 UTC, quhie commented on app/authen/pages/Register.tsx
> +const styles = StyleSheet.create({
okay để em hieu đọc rồi áp dụng lại

2024-09-25 12:53 UTC, thanhnn16 requested changes
Đọc từng comment, làm từng cái.
Cái nào xong thì chọn `Resolve conversation`.
cái nào không hiểu thì comment lại.

2024-09-25 12:53 UTC, thanhnndev commented on app/authen/OTP.tsx
> +Colors.loadColors({
lỡ làm này rùi em Hiêu tạo 1 file custom color luôn đi em Hiếu.

2024-09-25 12:53 UTC, thanhnndev commented on app/authen/OTP.tsx
> +      source={require('../../../assets/images/authen/img_bg_authen.png')}
https://wix.github.io/react-native-ui-lib/docs/foundation/assets
Dùng cái này nè e Hiếu

2024-09-25 12:53 UTC, thanhnndev commented on app/authen/Onboarding.tsx
> +const commonButtonStyle = {
không tạo cái này. nếu sửa custombutton trong này e Hiếu sửa custom button ở cái component luôn cho nó giống là được.
xem thêm: https://wix.github.io/react-native-ui-lib/docs/components/controls/Button
chiều rộng của nút là toàn màn hình nhưng khung bên ngoài là horizontal padding 24.

2024-09-25 12:53 UTC, thanhnndev commented on app/authen/Onboarding.tsx
> +const styles = {
không tạo style. đã dùng lib rồi mà.
https://wix.github.io/react-native-ui-lib/docs/components/basic/Text

2024-09-25 12:53 UTC, thanhnndev commented on app/authen/Onboarding.tsx
> +const styles = {
https://wix.github.io/react-native-ui-lib/docs/foundation/style

2024-09-25 12:53 UTC, thanhnndev commented on app/authen/OTP.tsx
> +Colors.loadColors({
https://wix.github.io/react-native-ui-lib/docs/foundation/assets
https://wix.github.io/react-native-ui-lib/docs/foundation/colors

2024-09-25 12:53 UTC, thanhnndev commented on app/authen/Onboarding.tsx
> +  style={{
như trên, không dùng style. xin hãy đọc docs

2024-09-25 12:53 UTC, thanhnndev commented on app/authen/Register.tsx
> +Colors.loadColors({
như file trên.

2024-09-25 12:53 UTC, thanhnndev commented on app/authen/Register.tsx
> +  const [fontsLoaded] = useFonts({
setup font từ đầu luôn: https://docs.expo.dev/develop/user-interface/fonts/

2024-09-25 12:53 UTC, thanhnndev commented on assets/images/logo/logoName.png
dùng file svg. đặt tên cho đúng.

2024-09-25 12:53 UTC, thanhnndev commented on git
xoá file này đi

2024-09-26 09:36 UTC, thanhnn16 approved these changes
Tạm thời merge trước để tiến hành tính năng khác.
Sẽ refractor sau.

2024-09-26 09:37 UTC, quhie commented
👍

Vào Th 5, 26 thg 9, 2024 lúc 16:36 Nông Nguyễn Thành <
***@***.***> đã viết:

> ***@***.**** approved this pull request.
>
> Tạm thời merge trước để tiến hành tính năng khác.
> Sẽ refractor sau.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/thanhnn16/allure_spa_expo/pull/15#pullrequestreview-2330671560>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BHZ3EJNQJAGQPPGXM5GX7ITZYPIRVAVCNFSM6AAAAABOWCXGZ2VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDGMZQGY3TCNJWGA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-09-26 10:43 UTC, merged